/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'Warframe.x64.exe'
*/
#pragma once
#include <Windows.h>
#include <stdint.h>

extern "C" {
#include <lua/lstate.h>
}

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

struct lua_State;
struct name_st;

/* 356 */
struct __declspec(align(8)) struct_LClosure
{
  BYTE gap0[24];
  void *env;
  void *p;
  __int64 field_28;
  __int64 field_30;
  __int64 field_38;
  __int64 field_40;
  __int64 field_48;
  __int64 field_50;
  __int64 field_58;
  __int64 field_60;
  __int64 field_68;
};

/* 357 */
struct __declspec(align(8)) script_mng
{
  __int64 field_0;
  __int16 field_8;
  __int16 field_A;
  __int64 field_10;
  __int64 field_18;
  lua_State *L;
  __int64 field_28;
  __int64 field_30;
  __int64 field_38;
  __int64 field_40;
  __int64 field_48;
  __int64 field_50;
  __int64 field_58;
  __int64 field_60;
  __int64 field_68;
  __int64 field_70;
  __int64 field_78;
  __int64 field_80;
  __int64 field_88;
  __int64 field_90;
  __int64 field_98;
  __int64 field_A0;
  __int64 field_A8;
  __int64 field_B0;
  __int64 field_B8;
  __int64 field_C0;
  __int64 field_C8;
  __int64 field_D0;
  __int64 field_D8;
  __int64 field_E0;
  __int64 field_E8;
  __int64 field_F0;
  __int64 field_F8;
  __int64 field_100;
  __int64 field_108;
  __int64 field_110;
  __int64 field_118;
  __int64 field_120;
  __int64 field_128;
  __int64 field_130;
  __int64 field_138;
  __int64 field_140;
  __int64 field_148;
  __int64 field_150;
  __int64 field_158;
  __int64 field_160;
  __int64 field_168;
};

struct rawLuaData {
    uint8_t* data;
    size_t size;
    size_t remain;
};

/* 358 */
struct __declspec(align(8)) script_data
{
  __int64 gap0;
  __int64 field_8;
  name_st *name;
  int gap18;
  DWORD dword1C;
  char *path;
  __int64 gap28;
  __int64 field_30;
  __int64 field_38;
  __int64 field_40;
  __int64 field_48;
  void *script_bin;
  void *empty_bytecode;
  void *qword60;
};

/* 360 */
struct name_st
{
  __int64 field_0;
  __int64 field_8;
  char *_str;
};

